services:
  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  app:
    env_file:
      - .env.dev
    command: [
      wait-for-it, "db:5432", --,
      /usr/src/app/venv/bin/uvicorn,
      "app.main:app",
      "--reload",
      "--host", "0.0.0.0",
      "--port", "5000",
      "--log-level", "debug",
    ]
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app/app:ro

  redis:
    ports:
      - "6379:6379"

  celery:
    restart: always
    env_file:
      - .env.dev
    command: [
      /usr/src/app/venv/bin/celery, -A, app.celery, worker,
      --prefetch-multiplier=1,
      --concurrency=2,
      --loglevel, INFO,
    ]
    volumes:
      - ./app:/usr/src/app/app:ro

  celery-beat:
    env_file:
      - .env.dev
    command: [
      /usr/src/app/venv/bin/celery, -A, app.tasks, beat,
      --loglevel, INFO,
      --schedule, /tmp/celerybeat-schedule.db
    ]
    volumes:
      - ./app:/usr/src/app/app:ro

  terracotta-db:
    env_file:
      - .env.dev
    ports:
      - "5433:5432"

  terracotta-server:
    env_file:
      - .env.dev
    command: [
      /usr/src/app/venv/bin/gunicorn,
      "--bind", "0.0.0.0:5000",
      "--workers", "1",
      "--log-level", "debug",
      "app.tc_app:app",
    ]
    ports:
      - "5001:5000"

  nginx:
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/nginx.conf:ro
