services:
  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  app:
    env_file:
      - .env.dev
    command: [
      /usr/src/app/venv/bin/uvicorn,
      "app.main:app",
      "--reload",
      "--host", "0.0.0.0",
      "--port", "5000",
      "--log-level", "debug",
    ]
    ports:
      - "5000-5002:5000"
    volumes:
      - ./app:/usr/src/app/app:ro

  redis:
    ports:
      - "6379:6379"

  celery:
    env_file:
      - .env.dev
    command: [
      /usr/src/app/venv/bin/celery, -A, app.celery, worker,
      --prefetch-multiplier=1,
      --concurrency=2,
      --loglevel, DEBUG,
      -B
    ]
    volumes:
      - ./app:/usr/src/app/app:ro

  celery-beat:
    env_file:
      - .env.dev
    command: [
      /usr/src/app/venv/bin/celery, -A, app.tasks, beat,
      --loglevel, INFO,
      --schedule, /tmp/celerybeat-schedule.db
    ]


  nginx:
    ports:
      - "8080:8080"
