"""leuchtennummer_optional

Revision ID: 0f8349c4729a
Revises: 81904b250b67
Create Date: 2026-01-05 16:54:23.707823

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0f8349c4729a'
down_revision: str | None = '81904b250b67'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'station', 'leuchtennummer',
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'station', 'leuchtennummer',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
