"""add_buddy_check

Revision ID: 336ac2d653e7
Revises: b33581fc4fec
Create Date: 2025-06-04 19:28:24.651397

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '336ac2d653e7'
down_revision: str | None = 'b33581fc4fec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'buddy_check_qc',
        sa.Column(
            'measured_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column('station_id', sa.Text(), nullable=False),
        sa.Column(
            'air_temperature_qc_isolated_check',
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            'air_temperature_qc_buddy_check',
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            'relative_humidity_qc_isolated_check',
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            'relative_humidity_qc_buddy_check',
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            'atmospheric_pressure_qc_isolated_check',
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            'atmospheric_pressure_qc_buddy_check',
            sa.Boolean(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(['station_id'], ['station.station_id']),
        sa.PrimaryKeyConstraint('measured_at', 'station_id'),
    )
    op.create_index(
        op.f('ix_buddy_check_qc_measured_at'), 'buddy_check_qc', ['measured_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_buddy_check_qc_station_id'), 'buddy_check_qc', ['station_id'],
        unique=False,
    )
    op.create_index(
        'ix_buddy_check_qc_station_id_measured_at',
        'buddy_check_qc',
        ['station_id', 'measured_at'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_buddy_check_qc_station_id_measured_at',
        table_name='buddy_check_qc',
    )
    op.drop_index(op.f('ix_buddy_check_qc_station_id'), table_name='buddy_check_qc')
    op.drop_index(op.f('ix_buddy_check_qc_measured_at'), table_name='buddy_check_qc')
    op.drop_table('buddy_check_qc')
    # ### end Alembic commands ###
