"""modify stations table

Revision ID: bb45ada8f270
Revises: 360e9646b9d2
Create Date: 2025-12-30 13:52:25.856185

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bb45ada8f270'
down_revision: str | None = '360e9646b9d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'station', sa.Column(
            'atm41_sensor_orientation',
            sa.NUMERIC(),
            nullable=True,
            comment='the orientation (-angle) of the arm of the ATM41 sensor of the station from the mounting structure',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'sht35_sensor_orientation',
            sa.NUMERIC(),
            nullable=True,
            comment='the orientation (-angle) of the arm of the SHT35 sensor of the station from the mounting structure',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'surface_below_sensor',
            sa.Text(),
            nullable=True,
            comment='surface type directly below the sensor e.g. asphalt, grass, ...',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'mounting_structure_color',
            sa.Text(),
            nullable=True,
            comment='color of the mounting structure e.g. black, white, ...',
        ),
    )
    op.add_column('station', sa.Column('maintenance_notes', sa.Text(), nullable=True))
    op.drop_column('station', 'proximity_to_building')
    op.drop_column('station', 'mounting_structure_material')
    op.drop_column('station', 'artificial_heat_sources')
    op.drop_column('station', 'blg_sensor_distance_from_mounting_structure')
    op.drop_column('station', 'proximity_to_tree')
    op.drop_column('station', 'sensor_orientation')
    op.drop_column('station', 'mounting_structure_height_agl')
    op.drop_column('station', 'blg_sensor_height_agl')
    op.drop_column('station', 'mounting_structure_light_extension_offset')
    op.drop_column('station', 'mounting_structure_diameter')
    op.drop_column('station', 'proximity_to_parking')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'station', sa.Column(
            'proximity_to_parking',
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'station', sa.Column(
            'mounting_structure_diameter',
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
            comment='the diameter of the mounting structure at the mounting height',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'mounting_structure_light_extension_offset',
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
            comment='when mounted to a lantern post, the overhang of the lantern',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'blg_sensor_height_agl',
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
            comment='the mounting height of the black globe sensor of the station',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'mounting_structure_height_agl',
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
            comment='the total height of the mounting structure above ground level',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'sensor_orientation',
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment='the orientation (-angle) of the arm of the main component of the station (ATM41 or SHT35) from the mounting structure',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'proximity_to_tree',
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'station', sa.Column(
            'blg_sensor_distance_from_mounting_structure',
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
            comment='the distance of the black globe sensor of the station from the mounting structure',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'artificial_heat_sources',
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment='e.g. cars, buildings, ...',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'mounting_structure_material',
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment='The material the structure the sensor is mounted to is made of e.g. metal, wood, ...',
        ),
    )
    op.add_column(
        'station', sa.Column(
            'proximity_to_building',
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column('station', 'maintenance_notes')
    op.drop_column('station', 'sht35_sensor_orientation')
    op.drop_column('station', 'atm41_sensor_orientation')
    op.drop_column('station', 'surface_below_sensor')
    op.drop_column('station', 'mounting_structure_color')
    # ### end Alembic commands ###
