name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: setup database container
      run: |
        docker compose -f docker-compose.yml -f docker-compose.dev.yml --env-file .env.dev up -d --wait db
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: install tox
      run: pip install --upgrade tox tox-uv
    - name: Prime the database
      run: tox -e prime_db
    - name: run tests in tox
      run: tox -e py
